### PR TITLE
update api to v1beta1

### PR DESCRIPTION
**Pull request by cpanato**
Signed-off-by: Carlos Panato <ctadeu@gmail.com>

**What this PR does / why we need it**:
-  update api to v1beta1
- also add initial config to use Tilt

/kind feature
/kind api-change

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
 update api to v1beta1
```

### CODE REVIEW

**Comment by cpanato** [comment]
need this in order to have the verify job to pass https://github.com/kubernetes/repo-infra/pull/244

**Comment by fabriziopandini** [comment]
@cpanato thanks for the heads up, great news!

**Review by timoreimann — APPROVED** [review]
This is awesome Carlos, thank you so much.

/lgtm
/approve

**Comment by cpanato** [comment]
all tests are green

will prepare the first release this week

/hold cancel

**Pull request merged**
