### PR TITLE
Update OWNERS

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

After discussing with other project maintainers, we have decided the following:

* I'll be stepping down as a project maintainer
* Promote Timo Reimann (@timoreimann) to a project maintainer

The lazy consensus for this change is 7 days from now, Monday, February 15th, 20:00 CET.

**Release note**:
```release-note
NONE
```

cc @cpanato @MorrisLaw @prksu @timoreimann

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
thanks Marko for all your work on this project!
welcome Timo

/lgtm

**Comment by timoreimann** [comment]
Very excited to be joining you soon as a maintainer! 🎉

**Review by prksu — APPROVED** [review]
/lgtm

@xmudrii I think the lazy consensus is over. Thanks for all your amazing work 🙇🏻 
And congrats @timoreimann 🎉

**Comment by xmudrii** [comment]
@prksu That's right, the lazy consensus is now over. :slightly_smiling_face: 

Welcome to the team @timoreimann! :tada:

I'll create PRs to update OWNERS in other places later today.

/hold cancel

**Comment by timoreimann** [comment]
🎉  thrilled to be joining this fine bunch of folks. 😄 

@xmudrii thanks for your all hard work in CAPDO, truly appreciated 💙

**Pull request merged**
