### PR TITLE
capi: using released artifacts

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
Using the release CAPI artifacts, the images was not published so that was failing, now it is live and we can use the released artifacts 

/assign @prksu @timoreimann @MorrisLaw 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Review by prksu — APPROVED** [review]
seem [these changes](https://github.com/kubernetes-sigs/cluster-api/pull/4558/files#diff-9857ab49578961f27c15575bff7f6aaed1c93603d5856905e3d5eecfd3642942R75-R79) broke our `capi-e2e` test.

never mind, `capi-e2e` test is an optional test.
/lgtm

**Comment by cpanato** [comment]
let me follow up on that, will open a new PR to check this

**Comment by cpanato** [comment]
and we should make the e2e mandatory

**Comment by cpanato** [comment]
ahh this is the capi test, will check that

**Pull request merged**
