### PR TITLE
go update to 1.16.13 and some dependencies updates

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:

- go update to 1.16.13
- some dependencies updates

/assign @MorrisLaw @timoreimann @prksu 

/hold for non required tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

n/a

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
- go update to 1.16.13
- some dependencies updates
```

### CODE REVIEW

**Review by MorrisLaw — APPROVED** [review]
/lgtm

**Review by MorrisLaw — APPROVED** [review]

**Comment by cpanato** [comment]
all good

/hold cancel

**Pull request merged**
