### PR TITLE
Make error handling consistent for the remaining packages

### PR DESCRIPTION
**Pull request by solidnerd**
Signed-off-by: solidnerd <niclas@mietz.io>

**What this PR does / why we need it**:

This will resolve a part of #109 and will format the last errors without values.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partly #109

### CODE REVIEW

**Comment by solidnerd** [comment]
I signed it

**Comment by nikhita** [comment]
Oh yeah, @xmudrii mentioned that #126 is required for tests to pass.

@solidnerd This should get merged once #126 is merged. :white_check_mark:

**Comment by solidnerd** [comment]
@nikhita  thanks for reviewing this. Yeah it's okay it doesn't stress me  😄 .

**Comment by xmudrii** [comment]
@solidnerd Thanks for the PR! The reason why this particular test is failing is because gofmt is failing on some package. If you run gofmt and push a fix, tests should start passing again regardless of #126.

However, I would put this on hold until #126 is not merged if you don't mind. It's a huge PR and currently in review phase, so I would like first to get done with that one and then get back to merging other PRs. 

/hold

**Comment by xmudrii** [comment]
The PR #126 is now merged, so I'm going to remove hold from this PR.
/hold cancel

@solidnerd Once the fmt error is fixed I'll be happy to merge this PR :)

**Comment by nikhita** [comment]
Bumping this.

@solidnerd do you think you can get to the fmt error soon? we could merge this after that :)

**Comment by solidnerd** [comment]
@nikhita  done ;)

**Comment by xmudrii** [comment]
Thanks!

/lgtm
/approve

**Pull request merged**
