### PR TITLE
Remove CircleCI in favour of Prow

### PR DESCRIPTION
**Pull request by nikhita**
Prow is enabled for this repo in https://github.com/kubernetes/test-infra/pull/9954.

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by nikhita** [comment]
/hold
until https://github.com/kubernetes/test-infra/pull/9954 has merged and we have verified that Prow tests work fine

/uncc @andrewsykim 
/cc @alvaroaleman

**Comment by xmudrii** [comment]
closing and reopening to verify tide and prow

**Comment by nikhita** [comment]
/hold cancel
because lgtm is gone anyway

@xmudrii Ptal.

The tests are green. :heavy_check_mark: I'll ask the admins to remove the circle ci webhook on this repo after this gets merged.

**Comment by xmudrii** [comment]
/lgtm
/approve

/hold
I want to check something with @nikhita before merging the PR

**Pull request merged**
