### PR TITLE
update dependencies and capi to 0.4.2

### PR DESCRIPTION
**Pull request by cpanato**
Signed-off-by: Carlos Panato <ctadeu@gmail.com>

**What this PR does / why we need it**:
update dependencies and capi to 0.4.2

to prepare a v1alpha4 release

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
update dependencies and capi to 0.4.2
```

### CODE REVIEW

**Review by MorrisLaw — APPROVED** [review]

**Comment by cpanato** [comment]
all tests passed
/hold cancel

**Pull request merged**
