### PR TITLE
Replace glog with klog

### PR DESCRIPTION
**Pull request by solidnerd**
Signed-off-by: solidnerd <niclas@mietz.io>

**What this PR does / why we need it**:
These are the next steps of #104 . This will enable us to use later the upstream cluster api again.

### CODE REVIEW

**Comment by xmudrii** [comment]
@solidnerd Thanks for the PR!

This looks good. I just have a question: is there anything that needs to be done to initialize `klog`, e.g. [this](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/cmd/manager/main.go#L42)? I was not following switch to `klog` lately, so I'm not sure is it and when is it needed, or is there anything else needed.

Also, if you're interested, `cmd/manager` package can also be updated to use `klog` instead of `log` if possible.

**Comment by solidnerd** [comment]
@xmudrii 

I think we need klog at least for the latest changes of the cluster api project. I tried to update the cluster api deps (https://github.com/kubernetes-sigs/cluster-api/commit/ca5119c1fb5b90a4b3455a63e7bce58fe35a6fe6)

When I want to start the clusterctl I get the following error:

```
bin/clusterctl flag redefined: log_dir
panic: bin/clusterctl flag redefined: log_dir

goroutine 1 [running]:
flag.(*FlagSet).Var(0xc0000a6120, 0x23a91a0, 0x3177ef0, 0x21a60a0, 0x7, 0x21da066, 0x2f)
        /usr/local/Cellar/go/1.12/libexec/src/flag/flag.go:850 +0x4af
flag.(*FlagSet).StringVar(...)
        /usr/local/Cellar/go/1.12/libexec/src/flag/flag.go:753
sigs.k8s.io/cluster-api-provider-digitalocean/vendor/k8s.io/klog.InitFlags(0xc0000a6120)
        /Users/niclas/go/src/sigs.k8s.io/cluster-api-provider-digitalocean/vendor/k8s.io/klog/klog.go:411 +0xa4
sigs.k8s.io/cluster-api-provider-digitalocean/vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd.init.14()
        /Users/niclas/go/src/sigs.k8s.io/cluster-api-provider-digitalocean/vendor/sigs.k8s.io/cluster-api/cmd/clusterctl/cmd/root.go:55 +0x31
```

When I added my changes for klog everything went fine.

**Comment by xmudrii** [comment]
@solidnerd Thanks a lot for the update! It looks good in this case, I'll go ahead and merge the PR.

/lgtm
/approve

**Pull request merged**
