### PR TITLE
dependencies: update several dependencies

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
Update dependencies:

- Update `github.com/digitalocean/godo` dependency to [v1.37.0](https://github.com/digitalocean/godo/tree/v1.37.0) which is the latest available and has the [following changes](https://github.com/digitalocean/godo/releases/tag/v1.37.0)
- Update `github.com/onsi/ginkgo` dependency to [v1.13.0](https://github.com/onsi/ginkgo/tree/v1.13.0) which is the latest available and has the [following changes](https://github.com/onsi/ginkgo/releases/tag/v1.13.0)
- Update `github.com/onsi/gomega` dependency to [v1.10.1](https://github.com/onsi/gomega/tree/v1.10.1) which is the latest available and has the [following changes](https://github.com/onsi/gomega/releases/tag/v1.10.1)
- Update `github.com/golangci/golangci-lint` dependency to [v1.27.0](https://github.com/golangci/golangci-lint/tree/v1.27.0) which is the latest available and has the [following changes](https://github.com/golangci/golangci-lint/releases/tag/v1.27.0)
- Update `github.com/golang/groupcache` dependency to `v0.0.0-20200121045136-8c9f03a8e57e`
- Update `golang.org/x/crypto` dependency to `v0.0.0-20200604202706-70a84ac30bf9`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
- Update `github.com/digitalocean/godo` dependency to `v1.37.0`
- Update `github.com/onsi/ginkgo` dependency to `v1.13.0`
- Update `github.com/onsi/gomega` dependency to `v1.10.1`
- Update `github.com/golangci/golangci-lint` dependency to `v1.27.0`
- Update `github.com/golang/groupcache` dependency to `v0.0.0-20200121045136-8c9f03a8e57e`
- Update `golang.org/x/crypto` dependency to `v0.0.0-20200604202706-70a84ac30bf9`
```

### CODE REVIEW

**Comment by xmudrii** [comment]
@cpanato The E2E tests are failing. Could it be related to this bump?

**Comment by cpanato** [comment]
@xmudrii I dont know i will setup a test PR to validate and check this bump one by one, bear with me :)

**Comment by cpanato** [comment]
if not pass in this time i'm going to revert some updates

**Comment by prksu** [comment]
bump, it passed now :grinning: 

/lgtm
thanks @cpanato

**Pull request merged**
