### PR TITLE
upgrade to capi 1.6.x

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:

- upgrade to capi 1.6.x

**Release note**:

```release-note
upgrade to capi 1.6.x
```

### CODE REVIEW

**Comment by cpanato** [comment]
the `pull-cluster-api-provider-digitalocean-e2e-workload-upgrade` looks like is broken and i need to check that, but it is a non blocking, so we can move forward

ptal 
/assign @timoreimann @gottwald 

after this will release 1.6

**Review by gottwald — APPROVED** [review]

**Pull request merged**
