### PR TITLE
Test CI

### PR DESCRIPTION
**Pull request by prksu**
Just triggering CI

Our periodic job has been a failure since 02-18
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-digitalocean#periodic-conformance-v1alpha3
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-provider-digitalocean#periodic-do-janitor

### CODE REVIEW

**Comment by prksu** [comment]
friendly ping @kubernetes-sigs/cluster-api-provider-digitalocean-maintainers 

```
Error: POST https://api.digitalocean.com/v2/account/keys: 401 Unable to authenticate you.
```
seem there is something wrong with our CI credential. before following up this issue to sigs-testing do you guys know what happens?

**Comment by timoreimann** [comment]
My best guess is that we're not injecting the DO token properly (anymore). We need to figure out how that's supposed to work in prow. 

(For reference, [Slack convo](https://kubernetes.slack.com/archives/CTND9FHU2/p1614330232007700)).

**Comment by prksu** [comment]
already fixed here https://github.com/kubernetes/test-infra/issues/21111

**Pull request closed without merging**
