### PR TITLE
Support specifying VPC

### LINKED ISSUE #177: Support custom VPC
Digitalocean recently released a new feature VPC. Since the release of this feature by default some resources `eg: droplets` will be automatically assigned to the default VPC `(default-{region-slug})`. we need to add VPC configuration to the DOCluster object and must be used on the created resource when filled otherwise let Digitalocean assign to default VPC.

/kind feature

### PR DESCRIPTION
**Pull request by timoreimann**
**What this PR does / why we need it**:
This change adds a field to DONetwork specifying the VPC UUID and updates the controllers to pass the ID into droplet and load balancer create requests. That way, users can create custom VPCs and have their CAPI-managed clusters join them.

**Which issue(s) this PR fixes**:
Fixes #177

**Special notes for your reviewer**:
I was looking into writing a dedicated e2e test for this feature. The part I struggled with is how to customize the subnet definition in the `Cluster` resource and, more importantly, the subnet defined in the Calico config file. I _think_ I can solve the former by introducing another DO-specific environment variable, but not sure if the same pattern applies for the Calico config.

Happy to follow up on this before calling the PR done if anyone is willing to provide some guidance. Thanks!

**Release note**:
```release-note
Add support for specifying the VPC UUID
```

### CODE REVIEW

**Comment by prksu** [comment]
@timoreimann so the users should to create the vpc before using that right?
how about automatically creating vpc through docluster-controller. so users just configure the vpc spec under `DONetwork` that contains name and ip range entity.

**Comment by timoreimann** [comment]
@prksu I like the idea to let the controller manage the VPC. I'm also thinking though that some users may want to use a pre-existing VPC, in which case the controller should probably verify that the VPC exists. Any thoughts on covering both cases? (If so, then I could first tackle the simpler case of the two followed by the other in a future PR.)

**Review by cpanato — APPROVED** [review]
/approve

**Comment by timoreimann** [comment]
@prksu I moved the VPC UUID below a newly created struct named `VPC`. This should provide space for adding more VPC-specific fields, like the subnet.

WDYT about getting this PR in first so that users who are fine with specifying the VPC ID explicitly and configuring the subnet etc. accordingly can benefit from it, while we leave the more complex auto-discovery approach to a future PR? The latter still has a few open questions for me, especially how a dynamically retrieved subnet can be fed into the CNI configuration. We might need more time to sort that out.

**Review by prksu — APPROVED** [review]
> @prksu I moved the VPC UUID below a newly created struct named VPC. This should provide space for adding more VPC-specific fields, like the subnet.

That's what I thought too.
And yes, we can leave the rest as the follow up. Thanks @timoreimann 

/lgtm

**Pull request merged**
