### PR TITLE
[release-0.5] Update go and capi

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
- update go to 1.16.13
- update capi to release v0.4.7

capi update due the cert manager issue https://kubernetes.slack.com/archives/C8TSNPY4T/p1643801670063279

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
- update go to 1.16.13
- update capi to release v0.4.7
```

### CODE REVIEW

**Comment by cpanato** [comment]
need this pr https://github.com/kubernetes/test-infra/pull/25103

**Review by prksu — APPROVED** [review]
/lgtm

**Pull request merged**
