### PR TITLE
Initial unit test for cloud/services packages

### PR DESCRIPTION
**Pull request by prksu**
**What this PR does / why we need it**:
This PR is initial work for adds unit tests in `cloud/services` packages. The rest of the tests will be added as a follow-up

**Release note**:

```release-note
None
```

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm
/hold for more eyes

**Review by MorrisLaw — APPROVED** [review]
:+1:

**Comment by MorrisLaw** [comment]
Closing this out because the changes from this PR were merged with PR [#450 ](https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/450).

**Pull request closed without merging**
