### PR TITLE
[WIP] Migrate dep to go modules

### PR DESCRIPTION
**Pull request by joonas**
**What this PR does / why we need it**: 

Go modules have become the standard way to manage dependencies across the various cluster-api ([capi](https://github.com/kubernetes-sigs/cluster-api/blob/master/go.mod), [capa](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/master/go.mod), [capz](https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/go.mod), [capg](https://github.com/kubernetes-sigs/cluster-api-provider-gcp/blob/master/go.mod), [capo](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/master/go.mod)) projects. It seems to me that it would make sense to follow suit for the sake of standardizing.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by joonas** [comment]
I reckon it would be best to get #138 merged in before proceeding with this one.

**Comment by cpanato** [comment]
this PR is still active? what we need to do to move forward?

**Comment by xmudrii** [comment]
@cpanato @joonas This PR depends on #138. Since we are migrating to CAPI `v1alpha2` which brings significant changes to the project and includes both this PR and #138, should we close this PR or merge it anyways?

I'm planning to do a snapshot of the current master (`v1alpha1`) and then I think we will not accept any changes afterward. If you'd like to see gometalinter and Go modules in the `v1alpha1` version, then we can merge both PRs, otherwise, I'll eventually close them.

**Comment by cpanato** [comment]
@xmudrii if we will not change this anymore maybe doe snot worth to effort to get this and the other merged and focus on that v1alpha2

**Comment by xmudrii** [comment]
Closing this PR in favor of #140.
/close

**Pull request closed without merging**
