### PR TITLE
Add IPFamily to fix CAPI test

### PR DESCRIPTION
**Pull request by prksu**
**What this PR does / why we need it**:

Add IPFamily in the e2e config to fix capi test

**Release note**:

```release-note
None
```

### CODE REVIEW

**Comment by prksu** [comment]
/assign @cpanato 
seem the [other provider](https://github.com/kubernetes-sigs/cluster-api-provider-azure/commit/23039e8654865ecf75af6d0d558cc12c02436dd0) just fix this issue on their side instead of on capi side.

**Comment by cpanato** [comment]
thanks for this quick fix @prksu

**Review by cpanato — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
