### PR TITLE
Update dependencies and CAPI to 1.5

### PR DESCRIPTION
**Pull request by llDrLove**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
- Upgrade Kubernetes packages to 0.27.6
- Upgrade controller-runtime to v0.15.2
- Upgrade cluster-api to v1.4.5
- Upgrade CAPI to 1.4.5

**Special notes for your reviewer**:
NONE

**Documentation**:

NONE

**Release note**:

```release-note
Upgrade Kubernetes packages to 0.27.6
Upgrade controller-runtime to v0.15.2
Upgrade cluster-api to v1.5.2
Upgrade CAPI to 1.5.2
```

### CODE REVIEW

**Comment by cpanato** [comment]
@llDrLove can you please rebase?

**Comment by llDrLove** [comment]
@cpanato , I've rebased.

**Review by cpanato — APPROVED** [review]
cool
thank you!
/approve
/lgtm

**Pull request merged**
