### PR TITLE
node-image: update node image to use ubuntu 20.04 and k8s 1.20.10

### PR DESCRIPTION
**Pull request by cpanato**
Signed-off-by: Carlos Panato <ctadeu@gmail.com>

**What this PR does / why we need it**:

node-image: update node iamge to use ubuntu 20.04 and k8s 1.20.10

built new node images for CAPDO CI

```
$ doctl compute image list
ID          Name                                               Type        Distribution    Slug    Public    Min Disk
63624555    cluster-api-ubuntu-1804-v1.16.2-1589476338         snapshot    Ubuntu                  false     25
80071030    Cluster API Kubernetes v1.18.16 on Ubuntu 20.04    snapshot    Ubuntu                  false     25
93100171    Cluster API Kubernetes v1.20.10 on Ubuntu 20.04    snapshot    Ubuntu                  false     25
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
node-image: update node image to use ubuntu 20.04 and k8s 1.20.10
```

### CODE REVIEW

**Review by timoreimann — APPROVED** [review]
/lgtm
/approve

**Comment by cpanato** [comment]
will figure out why is failing

**Comment by cpanato** [comment]
aha!
```
reason: InstanceCreatingError
	message: Failed to create droplet instance for DOMachine create-workload-cluster-49haqt/capdo-e2e-hg2uqs-control-plane-n4jjp: failed to create new droplet: POST https://api.digitalocean.com/v2/droplets: 422 (request "8ebc838a-4a4b-4253-a46c-92713563d734") Cannot create a droplet with a smaller disk than the image
```


will rebuild the image with a smaller disk to fit in the actual machines we are using

**Pull request merged**
