### PR TITLE
Upgrade ginkgo

### PR DESCRIPTION
**Pull request by cpanato**
**What type of PR is this?**

/kind feature
/kind cleanup

**What this PR does / why we need it**:

- update ginko to v2, CAPI to 1.3.x, go to 1.19 and certmanager to v1.10.1

need update the prow job
/hold for tests and make sure everything works

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squashed commits
- [ ] includes documentation
- [ ] adds unit tests

**Release note**:

```release-note
update ginko to v2, CAPI to 1.3.x, go to 1.19 and certmanager to v1.10.1
```

### CODE REVIEW

**Comment by cpanato** [comment]
prow job: https://github.com/kubernetes/test-infra/pull/28326

**Review by MorrisLaw — APPROVED** [review]
/lgtm

**Comment by cpanato** [comment]
fixed the upgrade tests @MorrisLaw can you take another look? thanks!

**Comment by cpanato** [comment]
ping @MorrisLaw

**Comment by cpanato** [comment]
also ping @timoreimann

**Review by timoreimann — APPROVED** [review]
/lgtm

**Pull request merged**
