### PR TITLE
Bump CAPI to V1.2.6 and Go to 1.18.8

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:

- Bump CAPI to V1.2.6 and Go to 1.18.8
/kind feature
/assign @timoreimann @MorrisLaw 
/hold for non required tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
Bump CAPI to V1.2.6 and Go to 1.18.8
```

### CODE REVIEW

**Comment by cpanato** [comment]
wrong PR sorry

/unassign @dims @richardcase @sbueringer @fabriziopandini

**Comment by sbueringer** [comment]
Np, Took a quick look. Changes look reasonable to me

**Pull request merged**
