### PR TITLE
🏃dependencies: update several dependencies

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:

- Update `digitalocean/godo` dependency to [v1.35.1](https://github.com/digitalocean/godo/tree/v1.35.1) which is the latest available and has the [following changes](https://github.com/digitalocean/godo/releases/tag/v1.35.1)
- Update `onsi/ginkgo` dependency to [v1.12.0](https://github.com/onsi/ginkgo/tree/v1.12.0) which is the latest available and has the [following changes](https://github.com/onsi/ginkgo/releases/tag/v1.12.0)
- Update `onsi/gomega` dependency to [v1.9.0](https://github.com/onsi/gomega/tree/v1.9.0) which is the latest available and has the [following changes](https://github.com/onsi/gomega/releases/tag/v1.9.0)
- Update `pkg/errors` dependency to [v0.9.1](https://github.com/pkg/errors/tree/v0.9.1) which is the latest available and has the [following changes](https://github.com/pkg/errors/releases/tag/v0.9.1)
- Update `go-yaml/yaml` dependency to [v2.2.8](https://github.com/go-yaml/yaml/tree/v2.2.8) which is the latest available and has the [following changes](https://github.com/go-yaml/yaml/releases/tag/v2.2.8)

- Update `golang/mock` dependency to [v1.4.3](https://github.com/golang/mock/tree/v1.4.3) which is the latest available and has the [following changes](https://github.com/golang/mock/releases/tag/v1.4.3)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
- Update digitalocean/godo dependency to v1.35.1
- Update onsi/ginkgo dependency to v1.12.0
- Update onsi/gomega dependency to v1.9.0
- Update pkg/errors dependency to v0.9.1
- Update go-yaml/yaml dependency to v2.2.8
- Update golang/mock dependency to v1.4.3
```

### CODE REVIEW

**Comment by cpanato** [comment]
I will open another PR with the `golangci/golangci-lint` and the fixes for the new lints

**Comment by xmudrii** [comment]
/lgtm
:eyes:

**Pull request merged**
