### PR TITLE
Move cloud into pkg/cloud

### PR DESCRIPTION
**Pull request by xmudrii**
**What this PR does / why we need it**:

This PR moves the cloud package into pkg/cloud to conform to the cluster-api project structure.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes part of #83 

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
/hold
until rebase

**Comment by nikhita** [comment]
Lgtm, but will tag after the rebase.

**Comment by nikhita** [comment]
lol, Marko!

/lgtm

**Pull request merged**
