### PR TITLE
update capi to v1.1.0

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:

- update capi to v1.1.0
- which also fixes an issue with cert manager: https://kubernetes.slack.com/archives/C8TSNPY4T/p1643801670063279
- update godo dependency

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
n/a

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
update capi to v1.1.0
```

### CODE REVIEW

**Comment by cpanato** [comment]
ah triggered a wrong test that is not working yet (pull-cluster-api-provider-digitalocean-capi-e2e-experimental) so we can ignore that

**Review by MorrisLaw — APPROVED** [review]
/lgtm

**Pull request merged**
