### PR TITLE
tests/e2e: add remediation tests

### PR DESCRIPTION
**Pull request by cpanato**
Signed-off-by: Carlos Panato <ctadeu@gmail.com>

**What this PR does / why we need it**:

/kind feature

- tests/e2e: add remediation tests
/hold for capi tests
/assign @timoreimann @MorrisLaw @prksu 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Documentation**:

**Release note**:

```release-note
tests/e2e: add remediation tests
```

### CODE REVIEW

**Review by timoreimann — APPROVED** [review]
Good stuff. I wonder if we should try to switch over to using ClusterClass at some point.

/lgtm

**Comment by cpanato** [comment]
> Good stuff. I wonder if we should try to switch over to using ClusterClass at some point.
> 
> /lgtm

we can check what we need to do for that

**Pull request merged**
